# -*- coding: utf-8 -*-
"""SmartC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U38r7OO8PlQZ33q0lmnVbvwbPFTgGMIR
"""

!pip install reportlab
!pip install PyPDF2
!pip install qrcode
!pip install qrcode[pil]
!pip install --upgrade reportlab qrcode[pil]

nombre = input("Ingresa tu nombre: ")
dom = input("Ingresa tu domicilio: ")
rfc = input("Ingresa tu RFC")
curp = input("Ingresa tu curp")
puesto = input("Ingresa tu puesto: ")

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import qrcode
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image



def generar_contrato(nombre, dom, rfc, curp, puesto):
    # Configuración del documento PDF
    doc = SimpleDocTemplate("contrato.pdf", pagesize=letter, rightMargin=20)
    story = []

    # Estilos para los párrafos
    styles = getSampleStyleSheet()
    estilo_justificado = ParagraphStyle(name="Justificado", alignment=1)  # 1 para justificar


    # Texto del contrato dividido en párrafos
    texto_contrato = [
        "CONTRATO DE PRESTACIÓN DE SERVICIOS PROFESIONALES POR HONORARIOS,",
        "QUE CELEBRAN POR UNA PARTE LA UNIVERSIDAD JUÁREZ DEL ESTADO DE",
        "DURANGO, Y POR LA OTRA Y POR SUS PROPIOS DERECHOS LA C. {nombre},",
        "QUIENES CONVIENEN EN CELEBRAR EL PRESENTE CONTRATO AL TENOR DE LAS SIGUIENTES:",
        "",
        "D E C L A R A C I O N E S:",
        "",
        "LA UNIVERSIDAD JUÁREZ DEL ESTADO DE DURANGO, ES UNA INSTITUCIÓN PÚBLICA",
        "Y AUTÓNOMA, DOTADA DE PLENA CAPACIDAD JURÍDICA Y QUE TIENE OBLIGACIÓN DE",
        "CUMPLIR CON LOS FINES DE IMPARTIR EDUCACIÓN EN TODOS SUS GRADOS Y",
        "ASPECTOS; REALIZAR INVESTIGACIÓN CIENTÍFICA, PRINCIPALMENTE ACERCA DE LOS",
        "PROBLEMAS NACIONALES Y DEL ESTADO DE DURANGO Y FOMENTAR Y DIFUNDIR LA",
        "CULTURA EN TODOS SUS ASPECTOS, CONTANDO CON DOMICILIO LEGAL UBICADO",
        "EN: CONSTITUCIÓN #404 SUR, ZONA CENTRO, C.P. 34000, DURANGO, DGO., Y QUE",
        "REQUIRIENDO DE LOS CONOCIMIENTOS DE UNA PERSONA QUE PRESTE SUS",
        "SERVICIOS PROFESIONALES REALIZANDO FUNCIONES DE AUXILIAR DE PROYECTOS,",
        "ADSCRITO A LA SECRETARIA TÉCNICA DE RECTORÍA DE ESTA UNIVERSIDAD.",
        "",
        "LA C. {nombre} MANIFIESTA QUE CUENTA CON LOS",
        "CONOCIMIENTOS PROFESIONALES PARA DESEMPEÑAR EL SERVICIO REQUERIDO Y",
        "QUE ESTÁ DADO DE ALTA ANTE LAS AUTORIDADES FISCALES COMO PRESTADOR DE",
        "SERVICIOS, DE NACIONALIDAD MEXICANA CON REGISTRO FEDERAL DE",
        "CONTRIBUYENTES NÚMERO {rfc}, CURP {curp}, CON",
        "DOMICILIO EN {dom}, EN LA CIUDAD DE DURANGO, DURANGO.",
        "",
        "LOS CONTRATANTES, DE CONFORMIDAD CON LO DISPUESTO EN LOS ARTÍCULOS",
        "2486, 2487 Y 2495 DEL CÓDIGO CIVIL VIGENTE EN EL ESTADO, FORMALIZAN EL",
        "PRESENTE CONTRATO DE PRESTACIÓN DE SERVICIOS PROFESIONALES AL TENOR",
        "DE LAS SIGUIENTES:",
        "",
        "C L Á U S U L A S:",
        "",
        "PRIMERA.- LOS CONTRATANTES SE RECONOCEN MUTUAMENTE LA PERSONALIDAD",
        "CON LA QUE SE OBLIGAN PARA TODOS LOS EFECTOS LEGALES A QUE HAYA LUGAR.",
        "",
        "SEGUNDA.- LA C. {nombre}, SE COMPROMETE A PRESTAR EL",
        "SERVICIO PROFESIONAL CON FUNCIONES DE AUXILIAR DE PROYECTOS, ADSCRITO A",
        "LA SECRETARIA TÉCNICA DE RECTORÍA DE ESTA UNIVERSIDAD DENTRO DEL",
        "HORARIO QUE SE CONVENGA.",
        "",
        "TERCERA.- EL TIEMPO DE LA DURACIÓN DEL PRESENTE CONTRATO DE PRESTACIÓN",
        "DE SERVICIOS PROFESIONALES SERÁ POR EL TÉRMINO DE 11 MESES Y 15 DÍAS,",
        "CONTADO A PARTIR DEL DÍA 01 DE FEBRERO DE 2023 Y CONCLUIRÁ EL DÍA 15 DE",
        "ENERO DE 2024.",
        "",
        "CUARTA.- LA UNIVERSIDAD CUBRIRÁ AL PRESTADOR DE SERVICIOS PROFESIONALES",
        "A LA PRESENTACIÓN DEL RECIBO POR HONORARIOS EL IMPORTE",
        "CORRESPONDIENTE A LA CANTIDAD QUINCENAL DE $4312.75 (SON CUATRO MIL",
        "TRESCIENTOS DOCE PESOS 75/100 M.N.) VÍA DEPÓSITO BANCARIO LOS DÍAS 15 Y 31",
        "DE CADA MES, MENOS LOS IMPUESTOS CORRESPONDIENTES, Y TODA VEZ QUE LOS",
        "SERVICIOS QUE SE PRESTAN SON POR AÑO Y AL TERMINAR ESTE, TERMINA TAMBIÉN",
        "",
        "LA RELACIÓN DE TRABAJO, SE OTORGARA UNA GRATIFICACIÓN ESPECIAL POR ÚNICA",
        "OCASIÓN PAGADERA DURANTE EL MES DE DICIEMBRE 2023, CORRESPONDIENTE A 30",
        "DÍAS POR AÑO DE PRESTACIÓN DE SERVICIOS PROFESIONALES POR HONORARIOS,",
        "CANTIDAD LA CUAL PODRÁ COMPUTARSE DE MANERA PROPORCIONAL EN BASE A",
        "LOS DÍAS QUE PRESTO SUS SERVICIOS PROFESIONALES EN EL AÑO 2023, MENOS LOS",
        "IMPUESTOS CORRESPONDIENTES",
        "",
        "QUINTA.- LAS PARTES ACUERDAN QUE EN RELACIÓN A LA LEY DEL IMPUESTO SOBRE",
        "LA RENTA EN SUS ARTÍCULOS 94 FRACCIÓN V Y 96, SE APLIQUE EL TRATAMIENTO",
        "FISCAL DE HONORARIOS ASIMILABLES A SUELDOS ESTABLECIDO EN LA LEY EN",
        "MENCIÓN.",
        "",
        "SEXTA.- LAS PARTES PODRÁN DAR POR TERMINADO EL PRESENTE CONTRATO EN",
        "CUALQUIER TIEMPO, SIN RESPONSABILIDAD ALGUNA PARA CUALQUIERA DE ELLAS,",
        "CON LA ÚNICA SALVEDAD DE QUE DEBERÁN DAR AVISO POR ESCRITO CON QUINCE",
        "DÍAS DE ANTICIPACIÓN.",
        "",
        "PARA EL CASO DE CONTROVERSIA, LOS CONTRATANTES SE SOMETEN A LA",
        "JURISDICCIÓN DE LOS TRIBUNALES COMPETENTES EN ESTA CIUDAD DE DURANGO,",
        "ENTERADOS DE SU EFICACIA Y VALOR PROBATORIO, LO RATIFICAN Y FIRMAN PARA",
        "CONSTANCIA LOS QUE EN EL INTERVIENEN AL 22 DE MARZO DE 2023.",
        "",
        "POR LA UJED",
        "M.A.P. KEILA DALILA TORRES CEPEDA",
        "DIRECTORA DE DESARROLLO Y",
        "GESTIÓN DE RECURSOS HUMANOS",
        "EL PRESTADOR",
        "C. {nombre}",
        "TESTIGO",
        "DRA. PAOLA YAMILET HERRERA",
        "CORTES",
        "TESTIGO",
        "M.A. LAURA BETSABÉ GÓMEZ RUIZ",
        "C.C.P. M.A. EDLA ELENA WALLANDER GARCIA, CONTRALORÍA GENERAL",
        "C.C.P. M.A.P. KEILA DALILA TORRES CEPEDA DIRECTORA DE DESARROLLO Y GESTIÓN DE RECURSOS HUMANOS",
        "C.C.P. DR. FORTUNATO RODRIGUEZ ACOSTA, TESORERO GENERAL",
        "C.C.P. INTERESADO",
        # Aquí puedes agregar más párrafos si es necesario...
    ]

    y_position = 600  # Posición inicial en el eje Y


    for parrafo in texto_contrato:
        # Si el párrafo está vacío (indicando un salto de línea), agrega un espacio vertical.
        if parrafo == "":
            story.append(Spacer(4, 12))
        else:
          estilo = estilo_justificado
        p = Paragraph(parrafo.format(nombre=nombre, puesto=puesto, rfc=rfc, dom=dom, curp=curp), estilo_justificado)
        story.append(p)


    # Generar el código QR
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data("https://www.hlj.com/1-144-scale-hguc-type-100-hyakushiki-bann09049")  # Reemplaza con tu enlace o texto
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    # Guardar el código QR en un archivo temporal
    qr_filename = "codigo_qr.png"
    img.save(qr_filename)

    # Agregar el código QR al PDF
    qr_image = Image(qr_filename, width=150, height=150)
    story.append(qr_image)

    # Crea el documento PDF
    doc.build(story)

# Llama a la función generando_contrato con los datos proporcionados por el usuario
generar_contrato(nombre, dom, rfc, curp, puesto)

